packages:
  - 'sdk'
  - 'text'
  - 'desktop'
  - 'goose-binary/*'
  - 'goose2'

allowBuilds:
  '@modelcontextprotocol/ext-apps': true
  '@swc/core': true
  electron: true
  electron-winstaller: true
  esbuild: true

nodeLinker: hoisted
blockExoticSubdeps: false

overrides:
  react: "^19.2.4"
  react-dom: "^19.2.4"
