const SLOT_TO_FILE: Record<string, { file: string; component: string }> = {
  'button': { file: 'src/components/ui/button.tsx', component: 'Button' },
  'card': { file: 'src/components/ui/card.tsx', component: 'Card' },
  'card-header': { file: 'src/components/ui/card.tsx', component: 'CardHeader' },
  'card-title': { file: 'src/components/ui/card.tsx', component: 'CardTitle' },
  'card-description': { file: 'src/components/ui/card.tsx', component: 'CardDescription' },
  'card-action': { file: 'src/components/ui/card.tsx', component: 'CardAction' },
  'card-content': { file: 'src/components/ui/card.tsx', component: 'CardContent' },
  'card-footer': { file: 'src/components/ui/card.tsx', component: 'CardFooter' },
  'collapsible': { file: 'src/components/ui/collapsible.tsx', component: 'Collapsible' },
  'collapsible-trigger': { file: 'src/components/ui/collapsible.tsx', component: 'CollapsibleTrigger' },
  'collapsible-content': { file: 'src/components/ui/collapsible.tsx', component: 'CollapsibleContent' },
  'dialog': { file: 'src/components/ui/dialog.tsx', component: 'Dialog' },
  'dialog-trigger': { file: 'src/components/ui/dialog.tsx', component: 'DialogTrigger' },
  'dialog-portal': { file: 'src/components/ui/dialog.tsx', component: 'DialogPortal' },
  'dialog-overlay': { file: 'src/components/ui/dialog.tsx', component: 'DialogOverlay' },
  'dialog-content': { file: 'src/components/ui/dialog.tsx', component: 'DialogContent' },
  'dialog-close': { file: 'src/components/ui/dialog.tsx', component: 'DialogClose' },
  'dialog-header': { file: 'src/components/ui/dialog.tsx', component: 'DialogHeader' },
  'dialog-footer': { file: 'src/components/ui/dialog.tsx', component: 'DialogFooter' },
  'dialog-title': { file: 'src/components/ui/dialog.tsx', component: 'DialogTitle' },
  'dialog-description': { file: 'src/components/ui/dialog.tsx', component: 'DialogDescription' },
  'dropdown-menu': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenu' },
  'dropdown-menu-trigger': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuTrigger' },
  'dropdown-menu-portal': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuPortal' },
  'dropdown-menu-content': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuContent' },
  'dropdown-menu-item': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuItem' },
  'dropdown-menu-checkbox-item': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuCheckboxItem' },
  'dropdown-menu-radio-group': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuRadioGroup' },
  'dropdown-menu-radio-item': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuRadioItem' },
  'dropdown-menu-label': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuLabel' },
  'dropdown-menu-separator': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuSeparator' },
  'dropdown-menu-shortcut': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuShortcut' },
  'dropdown-menu-group': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuGroup' },
  'dropdown-menu-sub': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuSub' },
  'dropdown-menu-sub-trigger': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuSubTrigger' },
  'dropdown-menu-sub-content': { file: 'src/components/ui/dropdown-menu.tsx', component: 'DropdownMenuSubContent' },
  'separator-root': { file: 'src/components/ui/separator.tsx', component: 'Separator' },
  'sheet': { file: 'src/components/ui/sheet.tsx', component: 'Sheet' },
  'sheet-trigger': { file: 'src/components/ui/sheet.tsx', component: 'SheetTrigger' },
  'sheet-close': { file: 'src/components/ui/sheet.tsx', component: 'SheetClose' },
  'sheet-portal': { file: 'src/components/ui/sheet.tsx', component: 'SheetPortal' },
  'sheet-overlay': { file: 'src/components/ui/sheet.tsx', component: 'SheetOverlay' },
  'sheet-content': { file: 'src/components/ui/sheet.tsx', component: 'SheetContent' },
  'sheet-header': { file: 'src/components/ui/sheet.tsx', component: 'SheetHeader' },
  'sheet-footer': { file: 'src/components/ui/sheet.tsx', component: 'SheetFooter' },
  'sheet-title': { file: 'src/components/ui/sheet.tsx', component: 'SheetTitle' },
  'sheet-description': { file: 'src/components/ui/sheet.tsx', component: 'SheetDescription' },
  'skeleton': { file: 'src/components/ui/skeleton.tsx', component: 'Skeleton' },
  'tooltip-provider': { file: 'src/components/ui/Tooltip.tsx', component: 'TooltipProvider' },
  'tooltip': { file: 'src/components/ui/Tooltip.tsx', component: 'Tooltip' },
  'tooltip-trigger': { file: 'src/components/ui/Tooltip.tsx', component: 'TooltipTrigger' },
  'tooltip-content': { file: 'src/components/ui/Tooltip.tsx', component: 'TooltipContent' },
};

export function lookupSlot(slot: string): { file: string; component: string } | null {
  return SLOT_TO_FILE[slot] ?? null;
}
